### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by malagsch** [beamtic/php-photo-gallery#4]
Hi

Since some days i have an problem and the page says HTTP ERROR 500
this happens after uploading a image.
the page was working now over 1 year without issues.
can you help me here?
or is there any new version already that is not published?

**Comment by jacobseated** [comment]
What do you get in your error log?

If using Apache:
/var/log/apache/mysite-error.log

The 500 error usually indicates a server-side problem.

**Comment by malagsch** [comment]
It was a png file that does the error.
i created the page new and started to upload picture by picture.
But why an png file is do this error and the site is not anymore reachable then

[Sun Sep 19 09:21:49.621368 2021] [php7:error] [pid 803] [client] PHP Fatal error:  Uncaught Error: Call to a member function string() on null in /var/www/html/index.php:181\nStack trace:\n#0 /var/www/html/index.php(94): createThumbnail('omida_startseit...', '/var/www/html/l...', '/var/www/html/t...', 400, 400)\n#1 /var/www/html/index.php(30): list_files(Array, Array)\n#2 {main}\n  thrown in /var/www/html/index.php on line 181, referer: https://mysite.dyndns.org/

[Sun Sep 19 09:21:50.040028 2021] [php7:warn] [pid 804] [client] PHP Warning:  session_cache_limiter(): Cannot change cache limiter when session is active in /var/www/html/index.php on line 11, referer: https://mysite.dyndns.org/

[Sun Sep 19 09:21:50.043942 2021] [php7:notice] [pid 804] [client] PHP Notice:  Undefined variable: translator in /var/www/html/index.php on line 181, referer: https://mysite.dyndns.org/

**Comment by jacobseated** [comment]
Perhaps the file is not a .png file? Sometimes files can have an inaccurate file-extension. Always make sure the file is trusted before uploading. There's only basic file-checks in place to make sure we are dealing with the right file.

I just corrected a few old bugs, so maybe you can try the latest version.

The galleries are now placed in the **gallery/** subdirectory, since this makes it much easier to update the source code directly from my local development installation. Unfortunately, this will also result in 404 errors with search engines, if you do not redirect the old directories to the new location. For .htaccess you can do like this:

`Redirect 301 /my-gallery-name/ /gallery/my-gallery-name/
`

**Comment by jacobseated** [comment]
Not sure this is even an error. Closing.
